annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
apiVersion: v2
appVersion: 20.4.0
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.5.2
description: A read-only system dashboard for multiple K8s clusters
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/kube-ops-view
icon: https://codeberg.org/repo-avatars/677-c51f6426305941cab515fdd98368f0bb
keywords:
- kube-ops-view
kubeVersion: '>=1.16.0-0'
maintainers:
- email: dennis.zhang.nrg@gmail.com
  name: FlipEnergy
name: kube-ops-view
sources:
- https://codeberg.org/hjacobs/kube-ops-view
version: 1.2.2
